version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctorgeondam-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/doctorgeondam
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - mysql
    restart: always
    networks:
      - doctorgeondam-network

  mysql:
    image: mysql:8.0
    container_name: doctorgeondam-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: doctorgeondam
      MYSQL_USER: codebrew
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - doctorgeondam-network

volumes:
  mysql-data:
    driver: local

networks:
  doctorgeondam-network:
    driver: bridge
